apiVersion: v1
kind: Service
metadata:
  labels:
    name: eventbuspublisherservice
  name: eventbuspublisherservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8097
      # port listened at inside the container
      targetPort: 8096
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: event-bus-publisher-ms
  type: NodePort