apiVersion: v1
kind: Service
metadata:
  labels:
    name: eventbuslistenerservice
  name: eventbuslistenerservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8096
      targetPort: 8096
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: event-bus-listener-ms
  type: NodePort